### ISSUE TITLE
Bogus quaternion returned by GamepadMotion.GetOrientation

### ISSUE THREAD

**Issue by Refragg** [JibbSmart/GamepadMotionHelpers#4]
Hello, I'm not entirely sure how to explain the problem so i think a video will help way more than any other explanation 

https://user-images.githubusercontent.com/38794835/196492240-2dd18c19-788a-4dc6-9f0c-657d876e1af2.mp4

So basically, it seems like some quaternion stuff has been broken for a bit, i did some testing and found that 164a5b55c9be22558dee141b952b5201d6a955af is the latest working commit for this (this is what the "old" library has been built against) from 8395bfebc3ecea8f5f40041be009335b5f03d5f9 to today (the "new" library was built on the latest commit), this issue is appearing.

This is not specific to this engine that we're building (i thought so at first), this has been tested in Unity aswell, Windows and Linux and it's the exact same problem, i've also tried both GamepadMotion.hpp and JoyShockLibrary's GetMotionState, same thing.

As for the used controller, it's a first-party DS4 from the original PS4 (has also been tested with later generation DS4 with the same problem)
  
**For the GamepadMotion.hpp, here's basically what we're doing:**
	
	Init:
	- create a GamepadMotion
	
	Frame Update:
	- use SDL_GameControllerGetSensorData to get gyro and accel values
	- transform gyro data to degrees per second and accel data to g-force
	- call GamepadMotion.ProcessMotion() with the transformed gyro / accel data and with our delta time
	- call GamepadMotion.GetOrientation()
	- change the quaternion rotation with the result from GetOrientation()
  
  
**For the JoyShockLibrary (built against the "new" and "old" GamepadMotion.hpp):**

	Init:
	- JslConnectDevices()
	- JslSetPlayerNumber(0, 1) (we only care about the first controller in this instance)

	Frame Update:
	- JslGetMotionState(0)
	- change the quaternion rotation with the result from JslGetMotionState(0)

I can try sharing at least the Unity project if you need, I'm down to help more and be proven wrong if you can get this working on newer versions of the header, maybe I'm doing something stupid here, i don't really know :p
  
Thanks in advance!

**Comment by JibbSmart** [comment]
Thanks so much for this info. I'll have a look when I can. My projects don't use the quaternion directly, so I missed this issue coming up with some of my changes.

**Comment by JibbSmart** [comment]
Sorry for the long delay, but this should be fixed in the latest version. I was multiplying two quaternions in the wrong order.
